version: '3.8'

services:
  nginx-gateway:
    build:
      context: ../../../
      dockerfile: api-gateway/docker/Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../../../api-gateway/config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../../../api-gateway/config/nginx/conf.d:/etc/nginx/conf.d:ro
      - ../../../api-gateway/config/ssl:/etc/nginx/ssl:ro
      - ../../../api-gateway/logs/nginx:/var/log/nginx
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    networks:
      - nginx-network
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  nginx-network:
    driver: bridge
